(setq default-directory "~/")
(setq inhibit-startup-message t)
(if (boundp 'window-system)
    (setq default-frame-alist
	  (append (list
		   '(foreground-color . "#e0e0e0")
		   '(background-color . "black"))
		  default-frame-alist)
	  )
  )
(setq initial-frame-alist default-frame-alist)
(set-frame-parameter (selected-frame) 'alpha '(0.85))
(menu-bar-mode -1)
(tool-bar-mode -1)
(setq frame-title-format
      (if (system-name)
          (format "%%f")
        (format "%%b")))
(global-linum-mode t)
(line-number-mode t)
(column-number-mode t)
(setq blink-cursor-mode nil)
;;(setq transient-mark-mode t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq-default line-spacing 0)
;;(set-scroll-bar-mode nil)
(setq initial-scratch-message "")
(global-font-lock-mode t)
;;(show-paren-mode t)
;;(setq show-paren-delay 0)
;;(setq show-paren-style 'expression)
(setq-default show-trailing-whitespace t)
(set-face-background 'trailing-whitespace "#b14700")
;;(setq set-face-background 'show-paren-match-face "#500")
;;(modify-frame-parameters nil '((scroll-bar-width . 14)))
(savehist-mode 1)
(setq history-length 3000)
(fset 'yes-or-no-p 'y-or-n-p)
(display-time-mode t)

(add-to-list 'load-path "~/.emacs.d/lisp/twittering-mode-3.0.0")
(require 'twittering-mode)
(setq twittering-use-master-password t)
(setq twittering-icon-mode nil)
(setq twittering-timer-interval 300)

